#! /usr/bin/env bash

function help {
    cat <<__EOF__

    usage: orcd apache [ on | off | restart | debug | new | del ]

    on: Turns on the apache webserver
    off: Turns off the apache webserver
    restart: Restarts the server gracefully
    debug: Use systemd to debug the apache service
    new: Writes a new virtual host under /etc/apache2/sites-available/
    del: Deletes a virtual host under /etc/apache2/sites-available/

__EOF__
}

function check_requirements {
    which apache2 > /dev/null 2>&1
	if [ "$?" -eq "0" ]; then
        # Duh
	    echo "[✔]::[apache2]: is installed!";
    else
        # Simple messages in case I turn into a moron someday
        echo "[x]::[warning]: Apache Breed requires apache!" ;
        echo "._. were you planning to use this without apache? wtf"
        echo "[!]::[please wait]: Installing apache for you..." ;
        sudo apt install apache2 -y
        echosleep 2
        echo ""
        clear
    fi
}

function del_mod {
    HOSTS_DIR="/etc/apache2/sites-available/"
    echo "Please input the (URL) for this virtual host"
    echo "Example: ventgrey.com"
    read -r url

    SITE_DIR="/var/www/${url}"
    sudo rm -rf "${SITE_DIR}"
    sudo rm "${HOSTS_DIR}/${url}.conf"
    echo "Virtual Host removed successfully"
}

function write_mod {
    HOSTS_DIR="/etc/apache2/sites-available/"
    echo "Please input the (URL) for this virtual host"
    echo "Example: ventgrey.com"
    read -r url

    SITE_DIR="/var/www/${url}/public_html"

    sudo mkdir -p "${SITE_DIR}"
    sudo chown -R www-data "${SITE_DIR}"

    sudo cat | tee >"${HOSTS_DIR}/${url}.conf" <<EOL
    <VirtualHost *:443>
                 ServerName ${url}
                 ServerAlias www.${url}

                 DocumentRoot  /var/www/${url}/public_html/

                 <Directory /var/www/${url}/public_html>
                            Options Includes
                            Options -FollowSymLinks -Indexes
                 </Directory>
    </VirtualHost>

    <VirtualHost *:80>
                 ServerName ${url}
                 ServerAlias www.${url}
                 Redirect permanent / https://{$url}
    </VirtualHost>
EOL

    sudo chmod 775 -R "${SITE_DIR}"
    echo "Virtual Host Written Successfully"
}

case $1 in
    help) help ;;

    on)
        # Just in case, "no vaya a ser"
        check_requirements;
        sudo systemctl start apache2 && sudo systemctl enable apache2 ;;

    off)
        check_requirements;
        sudo systemctl stop apache2 ;;

    restart)
        check_requirements;
        sudo apache2ctl graceful ;;

    debug)
        check_requirements;
        sudo journalctl -u apache2 ;;

    new)
        check_requirements;
        echo "This will assume you'll configure SSL later";
        write_mod ;;

    del)
        check_requirements;
        echo "This may result in data loss!";
        del_mod;;

    *) help;;
esac
# 2020 - VentGrey
