#!/bin/bash

# shellcheck source=../lib/requiem


function help {
    cat <<__EOF__

    usage: orcd apache [ on | off | restart | debug | new | del ]

    on: Turns on the apache webserver
    off: Turns off the apache webserver
    restart: Restarts the server gracefully
    debug: Use systemd to debug the apache service
    new: Writes a new virtual host under /etc/apache2/sites-available/
    del: Deletes a virtual host under /etc/apache2/sites-available/

__EOF__
}

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/requiem"

requirement apache2;

function del_mod {
    check_root
    HOSTS_DIR="/etc/apache2/sites-available/"
    echo "Please input the (URL) for this virtual host"
    echo "Example: ventgrey.com"
    read -r url

    SITE_DIR="/var/www/${url}"
    sudo rm -rf "${SITE_DIR}"
    sudo rm "${HOSTS_DIR}/${url}.conf"
    echo "Virtual Host removed successfully"
}

function write_mod {
    check_root
    HOSTS_DIR="/etc/apache2/sites-available/"
    echo "Please input the (URL) for this virtual host"
    echo "Example: ventgrey.com"
    read -r url

    SITE_DIR="/var/www/${url}/public_html"

    sudo mkdir -p "${SITE_DIR}"
    sudo chown -R www-data "${SITE_DIR}"

    sudo cat | tee >"${HOSTS_DIR}/${url}.conf" <<EOL
    <VirtualHost *:443>
                 ServerName ${url}
                 ServerAlias www.${url}

                 DocumentRoot  /var/www/${url}/public_html/

                 <Directory /var/www/${url}/public_html>
                            Options Includes
                            Options -FollowSymLinks -Indexes
                 </Directory>
    </VirtualHost>

    <VirtualHost *:80>
                 ServerName ${url}
                 ServerAlias www.${url}
                 Redirect permanent / https://{$url}
    </VirtualHost>
EOL

    sudo chmod 775 -R "${SITE_DIR}"
    echo "Virtual Host Written Successfully"
}

case $1 in
    help) help ;;

    on)
        check_root
        systemctl start apache2 && sudo systemctl enable apache2 ;;

    off)
        check_root
        systemctl stop apache2 ;;

    restart)
        check_root
        apache2ctl graceful ;;

    debug)
        check_root
        journalctl -u apache2 ;;

    new)
        check_root
        echo "This will assume you'll configure SSL later";
        write_mod ;;

    del)
        check_root
        echo "This may result in data loss!";
        del_mod;;

    *) help;;
esac
# 2020 - VentGrey
