#!/bin/bash

# shellcheck source=../lib/requiem

function help {
    cat <<__EOF__

    usage: orcd django [ setup | log | restart | backup]

    setup:   Creates and configures a Django
    log:     Show debug info for current django deployments
    restart: Restarts a django server gracefully
    backup:  Backs up a given Django instance
    help:    Show this screen
__EOF__
}

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/requiem"

case $1 in
    help) help ;;

    setup);;

    log);;

    restart);;

    backup);;

    *) help;;
esac

# Orchid 2020 - UpVent
