#!/bin/bash

# shellcheck source=../lib/requiem

function help {
    cat <<__EOF__

    usage: orcd django [ setup | log | restart | backup]

    setup:   Creates and configures a Django
    log:     Show debug info for current django deployments
    restart: Restarts a django server gracefully
    backup:  Backs up a given Django instance
    help:    Show this screen
__EOF__
}

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/requiem"


function setup() {

}

case $1 in
    help) help ;;

    setup)
        echo "Orchid will now attempt to configure a Django instance"
        echo "but first it needs you to input the following:"

        read -pr "Do you wish to setup a virtual environment?" virtenv
        read -pr "Are you using apache or nginx?" server
        read -pr "Choose your database engine: (Postgres | SQLite)" dbengine
        read -pr "Please input your default port for this Django app" djport
    ;;

    log);;

    restart);;

    backup);;

    *) help;;
esac

# Orchid 2020 - UpVent
