#!/bin/bash

# shellcheck source=../lib/requiem

function help {
    cat <<__EOF__

    # HIGHLY EXPERIMENTAL DO NOT TEST IN PRODUCTION ENVS

    usage: orcd docker [ on | off | restart | debug | new | del ]

    on: Turns on a docker container
    off: Turns off a docker container
    restart: Restarts a given container
    debug: Use systemd to debug the nginx service
    new: Writes a new server block under /etc/nginx/sites-available/
    del: Deletes a server block under /etc/nginx/sites-available/

__EOF__
}


source "$( dirname "${BASH_SOURCE[0]}" )/../lib/requiem"
