#! /usr/bin/env bash

function help {
    cat <<__EOF__

    usage: orcd kernel [ list | status | download | c-kernel
                       | cl-kernel | cy-kernel | llvm-kernel]

    list: Lists all installed kernels
    status: Shows current kernel information
    download: Downloads a kernel to /usr/src/
    c-kernel: Download and compile latest kernel.org kernel
    cl-kernel: Download and compile using localmodconfig kernel
    llvm-kernel: Download and compile latest kernel using clang

    WARNING: the *-kernel functions will produce .deb packages for installation.
             these will be kept in the user's $HOME dir.

__EOF__
}

function list_kernels {
    KNAME=$(uname -s)
    KTYPE=$(uname -r)
    KARCH=$(uname -m)
    KPROC=$(uname -p)

    apt_kernels=$(dpkg --list | grep linux-image)
    manual_kernels=$(ls -l /lib/modules/)

    echo "Running kernel:"
    echo "Kernel type: $KNAME"
    echo "Kernel version: $KTYPE"
    echo "Kernel arch: $KARCH"
    echo "Kernel proc: $KPROC"
    echo "------------------------------"
    echo "Kernels installed by apt:"
    echo "$apt_kernels"
    echo "------------------------------"
    echo "Manually installed kernels:"
    echo "$manual_kernels"
}


case $1 in
    help) help ;;

    list)
       list_kernels;;

    status)
         ;;

    download)
         ;;

    c-kernel)
         ;;

    cl-kernel)
         ;;

    llvm-kernel)
        ;;

    *) help;;
esac


# 2020 - VentGrey
