#!/bin/bash

# shellcheck source=../lib/requiem

function help {
    cat <<__EOF__

    usage: orcd nginx [ on | off | restart | debug | new | del ]

    on: Turns on the nginx webserver
    off: Turns off the nginx webserver
    restart: Restarts the server gracefully
    debug: Use systemd to debug the nginx service
    new: Writes a new server block under /etc/nginx/sites-available/
    del: Deletes a server block under /etc/nginx/sites-available/

__EOF__
}

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/requiem"

function del_mod {
    requirement nginx
    check_root
    HOSTS_DIR="/etc/nginx/sites-available"
    echo "Please input the (URL) for this server block"
    echo "Example: example.com"
    read -r url

    SITE_DIR="/var/www/${url}"
    rm -rf "${SITE_DIR}"
    rm "${HOSTS_DIR}/${url}"
    echo "Server Block removed successfully"
}

function write_mod {
    requirement nginx
    check_root
    HOSTS_DIR="/etc/nginx/sites-available/"
    echo "Please input the (URL) for this virtual host"
    echo "Example: example.com"
    read -r url

    SITE_DIR="/var/www/${url}/"

    mkdir -p "${SITE_DIR}"
    chown -R www-data "${SITE_DIR}"

    cat > "${HOSTS_DIR}/${url}" <<EOL
    server {
           listen 80 default_server;
           listen [::]:80 default_server;

           root /var/www/${url};
           index index.html index.htm index.nginx-debian.html;

           server_name _;

           location / {
                    try_files \$uri \$uri/ =404;
           }
    }
EOL

    chmod 775 -R "${SITE_DIR}"
    echo "Server Block Written Successfully"
}

case $1 in
    help) help ;;

    on)
        check_root
        systemctl start nginx && systemctl enable nginx ;;

    off)
        check_root
        systemctl stop nginx ;;

    restart)
        check_root
        systemctl reload nginx ;;

    debug)
        check_root
        journalctl -u nginx ;;

    new)
        check_root
        echo "This will assume you'll configure SSL later";
        write_mod ;;

    del)
        check_root
        echo "This may result in data loss!";
        del_mod;;

    *) help;;
esac
# 2020 - UpVent
