#!/usr/bin/env bash

# shellcheck source=../lib/requiem

help() {
    cat <<__EOF__

    usage: orcd prestashop [ setup | list | backup]

    setup:   Creates and configures a new prestashop instance
    list:    List all deployed prestashop instances
    backup:  Backs up a given prestashop instance
    help:    Show this screen
__EOF__

}

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/requiem"

setup_ps() {
    requirement apache2
    apt_requirement libapache2-mod-php

}

case $1 in
    help) help ;;

    setup) setup_ps ;;

    list) list_ps ;;

    backup) backup_ps ;;

    *) help;;
esac

# Orchid 2020 - UpVent
