#!/usr/bin/env bash

# shellcheck source=../lib/requiem
# shellcheck source=../lib/mist

help() {
    cat <<__EOF__

    usage: orcd virtual [ help | ubuntu | debian | centos | fedora ]

    ubuntu: Virtualize the latest ubuntu server (LTS)
    debian: Virtualize the latest Debian server
    centos: Virtualize the latest CentOS / CentOS Stream
    fedora: Virtualize the latest Fedora
    help:   Print this message

__EOF__
}

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/requiem"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/mist"

virt_ubuntu() {
    requirement kvm;
    requirement libvirt-bin;
    requirement virt-manager;
    requirement virt-viewer;
    requirement virt-top;
    requirement virt-what;

    fetch_distro ubuntu

    # Ask user for specifications
    read -pr "Input the virtual server name" vm_name
    echo
    read -pr "Input the number of CPU's for this virtual server" vm_cpu
    echo
    read -pr "Input the ram size (MB) for this virtual server" vm_ram
    echo
    read -pr "Input the disk size (GB) fo the vm" vm_disk
    echo

    # Create a new ubuntu instance using libmist
   new_virt "$vm_name" "$vm_cpu" "$vm_ram" "$vm_disk" "ubuntu"
}

virt_debian() {
    requirement kvm;
    requirement libvirt-bin;
    requirement virt-manager;
    requirement virt-viewer;
    requirement virt-top;
    requirement virt-what;

    fetch_distro debian

    # Ask user for specifications
    read -pr "Input the virtual server name" vm_name
    echo
    read -pr "Input the number of CPU's for this virtual server" vm_cpu
    echo
    read -pr "Input the ram size (MB) for this virtual server" vm_ram
    echo
    read -pr "Input the disk size (GB) fo the vm" vm_disk
    echo

    # Create a new ubuntu instance using libmist
   new_virt "$vm_name" "$vm_cpu" "$vm_ram" "$vm_disk" "debian"
}

virt_centos() {
    requirement kvm;
    requirement libvirt-bin;
    requirement virt-manager;
    requirement virt-viewer;
    requirement virt-top;
    requirement virt-what;

    fetch_distro centos

    # Ask user for specifications
    read -pr "Input the virtual server name" vm_name
    echo
    read -pr "Input the number of CPU's for this virtual server" vm_cpu
    echo
    read -pr "Input the ram size (MB) for this virtual server" vm_ram
    echo
    read -pr "Input the disk size (GB) fo the vm" vm_disk
    echo

    # Create a new ubuntu instance using libmist
   new_virt "$vm_name" "$vm_cpu" "$vm_ram" "$vm_disk" "centos"
}

virt_fedora() {
    requirement kvm;
    requirement libvirt-bin;
    requirement virt-manager;
    requirement virt-viewer;
    requirement virt-top;
    requirement virt-what;

    fetch_distro fedora

    # Ask user for specifications
    read -pr "Input the virtual server name" vm_name
    echo
    read -pr "Input the number of CPU's for this virtual server" vm_cpu
    echo
    read -pr "Input the ram size (MB) for this virtual server" vm_ram
    echo
    read -pr "Input the disk size (GB) fo the vm" vm_disk
    echo

    # Create a new ubuntu instance using libmist
   new_virt "$vm_name" "$vm_cpu" "$vm_ram" "$vm_disk" "fedora"
}

case $1 in
    help) help ;;

    ubuntu)
        check_root;
        virt_ubuntu;;

    debian)
        check_root;
        virt_debian;;

    centos)
        check_root;
        virt_centos;;

    fedora)
        check_root;
        virt_fedora;;

    *) help;;
esac
# 2020 - UpVent
