#!/bin/bash

# shellcheck source=../lib/requiem

function help {
    cat <<__EOF__

    usage: orcd virtual [ help | ubuntu | debian | centos | fedora | custom ]

    ubuntu: Virtualize the latest ubuntu server (LTS)
    debian: Virtualize the latest Debian server
    centos: Virtualize the latest CentOS / CentOS Stream
    fedora: Virtualize the latest Fedora
    custom: Virtualize a custom ISO
    help: Print this message

__EOF__
}

function virt_ubuntu() {
    requirement kvm;
    requirement libvirt-bin;
    requirement virt-manager;
    requirement virt-viewer;
    requirement virt-top;
    requirement virt-what;

    # Ask user for specifications
    read -pr "Input the virtual server name" vm_name
    echo
    read -pr "Input the number of CPU's for this virtual server" vm_cpu
    echo
    read -pr "Input the ram size (MB) for this virtual server" vm_ram


    # Create a new ubuntu instance using virt
    virt-install -name="Ubuntu" -vcpus=
}

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/requiem"

case $1 in
    help) help ;;

    ubuntu)
        check_root;
        systemctl start apache2 && systemctl enable apache2 ;;

    debian)
        check_root
        systemctl stop apache2 ;;

    centos)
        check_root
        apache2ctl graceful ;;

    fedora)
        check_root
        journalctl -u apache2 ;;

    custom)
        check_root
        write_mod ;;

    *) help;;
esac
# 2020 - UpVent
