#!/bin/bash

# shellcheck source=../lib/requiem

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/requiem"

function help {
    cat <<__EOF__

    usage: orcd wordpress [ apache | nginx ]

    apache: Installs a wordpress instance using Apache2.
    nginx: Installs a wordpress instance using nginx.

__EOF__
}

function wp_install {
    # Check for requirements
    requirement dialog
    requirement wget

    # Wordpress variables
    echo "Please input the (URL) for this wordpress site"
    echo "Example: example.com"
    read -r url

    wp_path="/var/www/${url}"
    wp_src="https://wordpress.org/latest.tar.gz"
    user="wpuser"
    database="wpdatabase"
    table="wp_"

}

case $1 in
    help) help ;;

    apache)
        check_root
        wp_install "apache";;

    nginx)
        check_root
        wp_install "nginx";;

    *) help;;
esac
