#!/bin/bash

function check_os {
    if type lsb_release >/dev/null 2>&1 ; then
        distro=$(lsb_release -i -s)
    elif [ -e /etc/os-release ] ; then
        distro=$(awk -F= '$1 == "ID" {print $2}' /etc/os-release)
    elif [ -e /etc/some-other-release-file ] ; then
        echo -e "Unsupported os-release file! Exiting..."
        exit 1
    fi

    distro=$(printf '%s\n' "$distro" | LC_ALL=C tr '[:upper:]' '[:lower:]')

    case "$distro" in
        debian*)  commands-for-debian ;;
        ubuntu*)  commands-for-ubuntu ;;
        mint*)    commands-for-mint ;;
        *)        echo -e "Unsupported distribution: '$distro'" ; exit 1 ;;
    esac
}

function requirement {
    command -v "$1" > /dev/null 2>&1
	if [ "$?" -eq "0" ]; then
	    echo -e "[\e[92m✔\e[39m]::[$1]: is installed!";
    else
        echo -e "[\e[1m\e[91mx\e[39m]::[ERROR]: This Breed requires $1!" ;
        exit 1
    fi
}

function check_root {
	[ "$(id -u)" -eq 0 ] && return "$TRUE" ||\
		echo -e "\e[31mThis module option must be run as root.\e[39m"; exit 1
}

# 2020 - UpVent
